# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqCFlhqijuJ48PiH93nrrqbKutIZSB4w
"""

# ==============================
# INSTALL (Colab only)
# ==============================
!pip install scikit-image tensorflow

# ==============================
# IMPORTS
# ==============================
import numpy as np
import cv2
import matplotlib.pyplot as plt
from google.colab import files
np.random.seed(42)

from skimage.metrics import peak_signal_noise_ratio, structural_similarity
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input, decode_predictions
from tensorflow.keras.preprocessing.image import img_to_array

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# ==============================
# RRAM FUNCTION
# ==============================
def rram_process(img, noise_level=0.05, alpha=1.2):
    G_min, G_max = 0.01, 1.0
    V = 0.2

    G = G_min + img * (G_max - G_min)

    noise = np.random.normal(0, noise_level * G)
    G_noisy = np.clip(G + noise, 0, None)

    G_nl = np.power(G_noisy, alpha)
    I = G_nl * V

    I_norm = (I - np.min(I)) / (np.max(I) - np.min(I) + 1e-8)

    return I_norm

# ==============================
# LOAD IMAGE
# ==============================
uploaded = files.upload()
img_path = list(uploaded.keys())[0]

img = cv2.imread(img_path)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_gray = cv2.resize(img_gray, (128,128)) / 255.0

# ==============================
# APPLY RRAM
# ==============================
rram_img = rram_process(img_gray)

# ==============================
# EDGE DETECTION
# ==============================
edges_original = cv2.Canny((img_gray*255).astype(np.uint8), 50, 150)
edges_rram = cv2.Canny((rram_img*255).astype(np.uint8), 50, 150)

# ==============================
# METRICS
# ==============================
psnr = peak_signal_noise_ratio(img_gray, rram_img)
ssim = structural_similarity(img_gray, rram_img, data_range=1.0)

print("PSNR:", psnr)
print("SSIM:", ssim)

# ==============================
# OBJECT RECOGNITION
# ==============================
model = MobileNetV2(weights='imagenet')

def predict(img_input):
    img_resized = cv2.resize(img_input, (224,224))
    img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)
    x = img_to_array(img_rgb)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    preds = model.predict(x)
    return decode_predictions(preds, top=1)[0][0]

orig_pred = predict(img)
rram_pred = predict((rram_img*255).astype(np.uint8))

print("\nOriginal Prediction:", orig_pred)
print("RRAM Prediction:", rram_pred)

# ==============================
# VISUALIZATION
# ==============================
plt.figure(figsize=(12,8))

plt.subplot(2,2,1)
plt.imshow(img_gray, cmap='gray')
plt.title("Original")

plt.subplot(2,2,2)
plt.imshow(rram_img, cmap='gray')
plt.title("RRAM Output")

plt.subplot(2,2,3)
plt.imshow(edges_original, cmap='gray')
plt.title("Edges Original")

plt.subplot(2,2,4)
plt.imshow(edges_rram, cmap='gray')
plt.title("Edges RRAM")

plt.show()

# ==============================
# CREATE SYNTHETIC DATASET (for ML graphs)
# ==============================
img_small = cv2.resize(img_gray, (32,32))

X = []
y = []

for i in range(200):
    noise = np.random.normal(0, 0.02, img_small.shape)
    sample = np.clip(img_small + noise, 0, 1)
    X.append(sample.flatten())
    y.append(i % 2)

X = np.array(X)
y = np.array(y)

# ==============================
# ACCURACY vs NOISE + ENERGY
# ==============================
noise_levels = [0, 0.05, 0.1, 0.2, 0.3]
acc_noise = []
energy_list = []

V = 0.2
G_min = 0.01
G_max = 1.0

for n in noise_levels:

    G = G_min + X * (G_max - G_min)

    if n == 0:
        noise = np.zeros_like(G)
    else:
        noise = np.random.normal(0, np.maximum(1e-9, n * G))

    G_noisy = np.clip(G + noise, 0, None) ** 1.2
    I = G_noisy * V

    energy = np.sum(V**2 * G_noisy)
    energy_list.append(energy)

    X_train, X_test, y_train, y_test = train_test_split(I, y, test_size=0.2)

    model_rf = RandomForestClassifier()
    model_rf.fit(X_train, y_train)

    y_pred = model_rf.predict(X_test)
    acc_noise.append(accuracy_score(y_test, y_pred))

# ==============================
# ACCURACY vs CONDUCTANCE LEVEL
# ==============================
levels = [2, 4, 8, 16, 32]
acc_levels = []

for L in levels:
    G = G_min + X * (G_max - G_min)

    G_quant = np.round(G * L) / L
    I = G_quant * V

    X_train, X_test, y_train, y_test = train_test_split(I, y, test_size=0.2)

    model_rf = RandomForestClassifier()
    model_rf.fit(X_train, y_train)

    y_pred = model_rf.predict(X_test)
    acc_levels.append(accuracy_score(y_test, y_pred))

# ==============================
# PLOTS
# ==============================

# Accuracy vs Noise
plt.figure()
plt.plot(noise_levels, acc_noise, marker='o')
plt.xlabel("RRAM Noise")
plt.ylabel("Accuracy")
plt.title("Accuracy vs RRAM Noise")
plt.grid()
plt.show()

# Energy vs Noise
plt.figure()
plt.plot(noise_levels, energy_list, marker='o')
plt.xlabel("RRAM Noise")
plt.ylabel("Energy")
plt.title("Energy vs Noise")
plt.grid()
plt.show()

# Accuracy vs Conductance
plt.figure()
plt.plot(levels, acc_levels, marker='o')
plt.xlabel("Conductance Levels")
plt.ylabel("Accuracy")
plt.title("Accuracy vs Conductance Levels")
plt.grid()
plt.show()

print("\nFINAL PROJECT EXECUTED SUCCESSFULLY 🚀")